package homework_10_Diana_Melkonyan;

public class MethNestTry {
    static void nesttry(int a){
        try{ //nested try block
            /* If one  command-line arg is used,
            then divide -by -zero exception will be generated by the following code. */
            if(a==1) a=a/(a-a); //division by zero


            /* If two  command-line args is used,
            then generate  an out-of- bounds exception  */
            if(a==2){
                int [] c = {1};
                c[42] = 99; //generate  an out-of- bounds exception

            }
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Array index out of bounds");
        }
    }

    public static void main(String[] args) {
        try{
            int a = args.length;
            int b = 42 /a;
            System.out.println("a = " + a);
            nesttry(a);
        }catch (ArithmeticException e){
            System.out.println("Divide by 0: " + e);
        }
    }
}
