package homework_18.Roza_Petrosyan;

import homework_18.Roza_Petrosyan.entity.Address;
import homework_18.Roza_Petrosyan.entity.User;

public class TestMap {
    public static void main(String[] args) {
        GenericMap<String, Integer> map = new GenericMap<>();
        map.put("a",-1);
        map.put("a",1);
        map.put("b",2);
        map.put("c",3);
        map.put("d",4);
        map.put("e",5);
        map.put("f",6);
        map.put("g",7);
        map.put("h",8);
        map.put("i",9);
        map.put("j",10);
        map.put("k",11);
        map.put("l",12);
        map.put("m",13);
        map.put("n",14);
        map.put("o",15);
        map.put("p",16);
        map.put("q",17);
        map.put("r",18);
        map.put("s",19);
        map.put("t",20);
        map.put("u",21);
        map.put("v",22);
        map.put("w",23);
        map.put("x",24);
        map.put("y",25);
        map.put("z",26);
        map.put("aa",27);
        map.put("bb",28);
        map.put("cc",29);
        map.put("dd",30);
        map.put("ee",31);
        map.put("ff",32);
        map.put("gg",33);
        map.put("hh",34);
        map.put("ii",35);
        map.put("gg",36);
        map.put("kk",37);
        map.put("ll",38);
        map.put("mm",39);
        map.put("nn",40);
        map.put("oo",41);
        map.put("pp",42);
        map.put("qq",43);
        map.put("rr",44);
        map.put("ss",45);
        map.put("tt",46);
        map.put("uu",47);
        map.put("vv",48);
        map.put("ww",49);
        map.put("xx",50);
        map.put("yy",51);
        map.put("A",52);
        map.put("B",53);
        map.put("C",54);
        map.put("D",55);
        map.put("E",56);
        map.put("F",57);
        map.put("G",58);
        map.put("H",59);
        map.put("I",60);
        map.put("J",61);
        map.put("K",62);
        map.put("L",63);
        map.put("M",64);
        map.put("N",65);
        map.put("O",66);
        map.put("P",67);
        map.put("Q",68);
        map.put("R",69);
        map.put("S",70);
        map.put("T",71);
        map.put("U",72);
        map.put("V",73);
        map.put("W",null);
        map.put("X",-75);
        map.put(null,76);
        map.put("X",75);
        System.out.println(map);
        System.out.println(map.get("a"));
        System.out.println(map.get("X"));
        System.out.println(map.get("one"));

        GenericMap<User, Integer> userMap = new GenericMap<>();
        User user1 = new User("Tom","Smith", 30, new Address("France","Paris", "2nd",15));
        User user2 = new User("John","Hoking", 27, new Address("UK","London", "1th",4));
        userMap.put(user1,1000);
        userMap.put(user2,2000);
        System.out.println(userMap);
        System.out.println(userMap.get(user1));
    }
}
