package homework_10.Nelli_Poghosyan;

public class MethNestTry {
    static void nestTry(int a){
        try{ //try nested block
            /* if one command -line arg is used,
            then a divide-by-zero exception
            will be generated by the following code.*/
            if(a==1 ) a = a/(a-a); //division by zero
            /*if two command-line args are used,
            then generate an out-of-bounds exception.
             */
            if(a==2){
                int[] c ={1};
                c[42] = 99;
            }
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Array index out-of-bounds: "+e);
        }
    }

    public static void main(String[] args) {
        try{
            int a = args.length;
            int b = 42/a;
            System.out.println("a = " + a);
            nestTry(a);
        }catch (ArithmeticException e){
            System.out.println("Divide by 0: "+e);
        }
    }
}
